#!/usr/bin/env bash

UNICODE_FILE_DIRECTORY="./data/unicode_expense_files"
TARGET_DIRECTORY="./data/expense_files/expensify"
UNICODE_FILES=$(ls $UNICODE_FILE_DIRECTORY | grep .csv$)

for UNICODE_FILE in $UNICODE_FILES; do
    #ls -l $UNICODE_FILE_DIRECTORY/$UNICODE_FILE
    mv $UNICODE_FILE_DIRECTORY/$UNICODE_FILE $UNICODE_FILE_DIRECTORY/$UNICODE_FILE.unicode
    iconv -c -f UTF-8 -t ASCII $UNICODE_FILE_DIRECTORY/$UNICODE_FILE.unicode > $TARGET_DIRECTORY/$UNICODE_FILE
done

exit 0
